---

- name: Create responder resource group
  azure_rm_resourcegroup:
    name: "{{ cloud_vpn_name }}-responder-resource-group"
    location: "{{ cloud_vpn_responder_azure_region }}"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"

- name: Create Azure responder provision stack
  azure_rm_deployment:
    resource_group: "{{ cloud_vpn_name }}-responder-resource-group"
    location: "{{ cloud_vpn_responder_azure_region }}"
    deployment_name: "{{ cloud_vpn_name }}-responder-provision-template"
    template: "{{ lookup('template', 'templates/cloud_vpn/provisioners/azure_vpn/responder/provision.j2') }}"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"

- name: Get Azure public IP facts
  azure_rm_publicipaddress_facts:
    name: "{{ cloud_vpn_name }}-responder-gw-ip"
    resource_group: "{{ cloud_vpn_name }}-responder-resource-group"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"
  register: out

- name: Set cloud_vpn_responder_public_ip fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ out.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"

